#### Data Source
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=
#spring.datasource.separator=^

#### Liquibase
spring.liquibase.change-log=classpath:database/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

#### JPA Hibernate
## disable automatic table generation via Hibernate
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none

## show logging of hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## jpa hibernate & postgresql
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## for schema.sql automatic create tables every time whent to run the programm
#spring.sql.init.mode=always